<?php

/**
 * Class-Backlinks.php
 *
 * @package Backlinks
 * @link
 * @author reslava <reslava@gmail.com>
 * @copyright 2023 reslava
 * @license https://opensource.org/licenses/MIT The MIT License
 *
 * @version 0.21
 */

namespace reslava;

if (!defined('SMF'))
	die('No direct access...');

/**
 * Generated by Simple Mod Maker
 */
class Backlinks
{		
	public function hooks()
	{
		// add_integration_function('integrate_hook_name', __CLASS__ . '::methodName#', false, __FILE__);
		add_integration_function('integrate_prepare_display_context', __CLASS__ . '::prepareDisplayContext#', false, __FILE__);
		add_integration_function('integrate_load_theme', __CLASS__ . '::integrateLoadTheme#', false, __FILE__);
		add_integration_function('integrate_recent_RecentPosts', __CLASS__ . '::integrate_recent_RecentPosts#', false, __FILE__);
	}
	
	/**
	 * @hook integrate_load_theme
	 **/	 
	public function integrateLoadTheme()
	{			
		loadLanguage('Backlinks');
		loadTemplate('Backlinks', 'backlinks');
	}
	/**
	 * @hook integrate_recent_RecentPosts
	 */
	public function integrate_recent_RecentPosts()
	{
		global $context;
		
		foreach ($context['posts'] as $key => $post)					
		{						
			if (Backlinks::hasBacklink($backlinks, $post['id']))				
				Backlinks::addButtons($backlinks, $context['posts'][$key]['quickbuttons']);					
		}
	}
	
	public function addButtons($backlinks, &$quickbuttons)
	{
		foreach ($backlinks as $key => $backlink)		
			Backlinks::addButton($backlink, $quickbuttons);		
	}
	
	public function addButton($backlink, &$quickbuttons)
	{
		$buttons = array(
			'backlinks' . $backlink => array(
			   'label' => '',
			   'href' => $scripturl . '?msg=' . $backlink . ';',
			   'icon' => 'backlink_button',
			   'class' => 'backlink_button_link',
			   'show' => true,
			)
		);
		$quickbuttons = array_merge($buttons, $quickbuttons);			
	}
	/**
	 * @hook integrate_prepare_display_context
	 */
	public function prepareDisplayContext(&$output, &$message, $counter)
	{
		global $context, $txt, $scripturl, $user_profile, $modSettings;								
		
		if (Backlinks::hasBacklink($backlinks, $message['id_msg']))				
			Backlinks::addButtons($backlinks, $output['quickbuttons']);			
	}	
	
	public function hasBacklink(&$backlinks, $id_msg)
	{					
		global $smcFunc, $context;									
		
		$results = $smcFunc['db_query']('', '
					SELECT * FROM {db_prefix}messages 
					WHERE (body REGEXP ".*msg=?({int:id_msg}#?[^0-9]).*") 					
					ORDER BY `id_msg` ASC
					LIMIT 5',
					array(												
						'id_msg' => $id_msg
					)
				);						
		
		if(!$results)
			return false;					
		
		$backlinks = array();
		while ($row = $smcFunc['db_fetch_row']($results))					
			$backlinks[] = $row[0]; 									
		
		$smcFunc['db_free_result']($results);
		if(count($backlinks) == 0)
			return false;	
		
		return true;		
	}
}